name: Docs Production Deployment - Netlify

env:
  GHA_DOCKER_TAG: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation
  NODE_VERSION: 20
  DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
  DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}

on:
  push:
    branches:
      - latest'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./latest/docs/

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1
        path: latest

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1
        with:
          ref: prod-docs-netlify
        path: prod-docs-netlify

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Dependencies
        run: |
          npm ci

      - name: Docker build
        run: |
          npm run docs:docker:build:production

      - name: Test examples
        run: |
          npm run docs:test:example-checker

      - name: checkout the latest
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1
          with:
            ref: latest
      - name: copy docs to the latest
        run: cp -r ../dist/* .
          working-directory: ./docs/tmp
      - name: list files in the repository
      run: ls ${{ github.workspace }}
      - name: deploy to Netlify
        steps:
          - uses: jsmrcaga/action-netlify-deploy@v2.0.0
            with:
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              build_directory: ./docs/tmp