name: Linter

on: [push]

env:
  NODE_VERSION: 16

jobs:
  build:
    name: JS & CSS & TS & D.TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # https://github.com/actions/setup-node/releases/tag/v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: JavaScript lint
        run: |
          npm run lint

      - name: CSS lint
        run: |
          npm run in handsontable stylelint
