name: Visual tests Linter

on:
  push:
    paths:
      - 'visual-tests/**'
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # https://github.com/actions/setup-node/releases/tag/v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install monorepo dependencies
        run: |
          npm ci --no-audit

      - name: Lint
        run: |
          npm run in visual-tests lint
